# Generated by Django 4.2.5 on 2024-01-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='licence_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
